blank_issues_enabled: false
contact_links:
  - name: Discord Server - GlitchLib
    url: https://discord.gg/nJJ2fDM
    about: This is a Official GlitchLib Discord Server. For mostly better support rather than spamming questions, please consider using this Discord Server. Created by owner @stachu540